package com.xschen.spring.jpa.overview.ch01_6.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * 单表多态示例，同一张 Table，表示了不同的对象，通过一个字段来进行区分
 * 本类作为父类，只有父类有 @Entity
 * @author xschen
 */

@Entity(name = "book")
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Data
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
// 鉴别值 color
@DiscriminatorColumn(name = "color", discriminatorType = DiscriminatorType.STRING)
public class Book {

    /**
     * create table book (
     *         color varchar(31) not null,
     *         id bigint generated by default as identity,
     *         title varchar(255),
     *         blue_mark varchar(255),
     *         red_mark varchar(255),
     *         primary key (id)
     *     )
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String title;

}
